In [562]:
import numpy as np
import pandas as pd

In [563]:
df=pd.read_csv("Churn_Modelling.csv")

In [564]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [565]:
df.shape

(10000, 14)

In [566]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [567]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [568]:
df.duplicated().sum()

np.int64(0)

In [569]:
(df['Exited']==0).value_counts()

Exited
True     7963
False    2037
Name: count, dtype: int64

In [570]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [571]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [572]:
df.drop(columns=["RowNumber","CustomerId","Surname"],inplace=True)

In [573]:
df=pd.get_dummies(df,columns=['Gender','Geography'],drop_first=True)

In [574]:
df.astype(int)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Male,Geography_Germany,Geography_Spain
0,619,42,2,0,1,1,1,101348,1,0,0,0
1,608,41,1,83807,1,0,1,112542,0,0,0,1
2,502,42,8,159660,3,1,0,113931,1,0,0,0
3,699,39,1,0,2,0,0,93826,0,0,0,0
4,850,43,2,125510,1,1,1,79084,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0,2,1,0,96270,0,1,0,0
9996,516,35,10,57369,1,1,1,101699,0,1,0,0
9997,709,36,7,0,1,0,1,42085,1,0,0,0
9998,772,42,3,75075,2,1,0,92888,1,1,1,0
9999,792,28,4,130142,1,1,0,38190,0,0,0,0

In [575]:
df.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Gender_Male',
       'Geography_Germany', 'Geography_Spain'],
      dtype='str')

In [576]:
X=df.drop(columns=['Exited'])

In [577]:
y=df['Exited']

In [578]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [579]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
X_train_scaled=scalar.fit_transform(X_train)
X_test_scaled=scalar.transform(X_test)

In [580]:
import torch.nn as nn
import torch.optim as optim

In [581]:
# model=nn.Sequential(
#     nn.Linear(11,3),
#     nn.Sigmoid(),
#     nn.Linear(3,1)
# )
model = nn.Sequential(
    nn.Linear(11, 16),
    nn.ReLU(),
    nn.Linear(16, 8),
    nn.ReLU(),
    nn.Linear(8, 1)
)
# model = nn.Sequential(
#     nn.Linear(11, 64),
#     nn.LeakyReLU(),
#     nn.Linear(64, 32),
#     nn.LeakyReLU(),
#     nn.Linear(32, 1)
# )

In [582]:
loss_fn=nn.BCEWithLogitsLoss()
optimizer=optim.Adam(model.parameters(),lr=0.03)

In [583]:
import torch
X_train_tensor=torch.tensor(X_train_scaled,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test_scaled,dtype=torch.float32)

In [584]:
y_train_tensor=torch.tensor(y_train.values,dtype=torch.float32).view(-1,1)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.float32).view(-1,1)

In [585]:
X_train_tensor.shape, y_train_tensor.shape

(torch.Size([8000, 11]), torch.Size([8000, 1]))

In [586]:
for epoch in range(100):
    
    outputs=model(X_train_tensor)
    
    loss=loss_fn(outputs,y_train_tensor)
    
    optimizer.zero_grad()
    loss.backward()
    
    optimizer.step()
    
    print(f"Epoch {epoch+1},Loss:{loss.item()}")

Epoch 1,Loss:0.6798871755599976
Epoch 2,Loss:0.6387637257575989
Epoch 3,Loss:0.5971608757972717
Epoch 4,Loss:0.5547712445259094
Epoch 5,Loss:0.5185106992721558
Epoch 6,Loss:0.49633708596229553
Epoch 7,Loss:0.488716185092926
Epoch 8,Loss:0.48623427748680115
Epoch 9,Loss:0.4800359606742859
Epoch 10,Loss:0.4700663685798645
Epoch 11,Loss:0.4595367908477783
Epoch 12,Loss:0.4509895145893097
Epoch 13,Loss:0.4456923305988312
Epoch 14,Loss:0.44322124123573303
Epoch 15,Loss:0.44248878955841064
Epoch 16,Loss:0.44236862659454346
Epoch 17,Loss:0.4420357346534729
Epoch 18,Loss:0.44107380509376526
Epoch 19,Loss:0.4395466446876526
Epoch 20,Loss:0.43775299191474915
Epoch 21,Loss:0.436073362827301
Epoch 22,Loss:0.4348294138908386
Epoch 23,Loss:0.43414220213890076
Epoch 24,Loss:0.43385395407676697
Epoch 25,Loss:0.43365105986595154
Epoch 26,Loss:0.4332403242588043
Epoch 27,Loss:0.43247920274734497
Epoch 28,Loss:0.43146347999572754
Epoch 29,Loss:0.4304169714450836
Epoch 30,Loss:0.4295901656150818
Epoch 31,Loss:0.4290721118450165
Epoch 32,Loss:0.42880862951278687
Epoch 33,Loss:0.42864468693733215
Epoch 34,Loss:0.4283920228481293
Epoch 35,Loss:0.4279284179210663
Epoch 36,Loss:0.4272463321685791
Epoch 37,Loss:0.42644914984703064
Epoch 38,Loss:0.4256449341773987
Epoch 39,Loss:0.42492222785949707
Epoch 40,Loss:0.42429932951927185
Epoch 41,Loss:0.4237213432788849
Epoch 42,Loss:0.42310595512390137
Epoch 43,Loss:0.4223763644695282
Epoch 44,Loss:0.4215694069862366
Epoch 45,Loss:0.42073899507522583
Epoch 46,Loss:0.41993463039398193
Epoch 47,Loss:0.41920551657676697
Epoch 48,Loss:0.41849374771118164
Epoch 49,Loss:0.41770631074905396
Epoch 50,Loss:0.41677695512771606
Epoch 51,Loss:0.4156748056411743
Epoch 52,Loss:0.41440483927726746
Epoch 53,Loss:0.41296765208244324
Epoch 54,Loss:0.4113571345806122
Epoch 55,Loss:0.40957844257354736
Epoch 56,Loss:0.407553493976593
Epoch 57,Loss:0.4052836000919342
Epoch 58,Loss:0.4028271436691284
Epoch 59,Loss:0.4000994563102722
Epoch 60,Loss:0.3971923589706421
Epoch 61,Loss:0.39416101574897766
Epoch 62,Loss:0.3908984959125519
Epoch 63,Loss:0.38742297887802124
Epoch 64,Loss:0.38387975096702576
Epoch 65,Loss:0.3804999589920044
Epoch 66,Loss:0.37758469581604004
Epoch 67,Loss:0.37507137656211853
Epoch 68,Loss:0.3731052875518799
Epoch 69,Loss:0.371518075466156
Epoch 70,Loss:0.36999014019966125
Epoch 71,Loss:0.368474543094635
Epoch 72,Loss:0.3670511841773987
Epoch 73,Loss:0.3658004403114319
Epoch 74,Loss:0.3646167814731598
Epoch 75,Loss:0.36349233984947205
Epoch 76,Loss:0.3624817430973053
Epoch 77,Loss:0.3616620600223541
Epoch 78,Loss:0.36084693670272827
Epoch 79,Loss:0.35999542474746704
Epoch 80,Loss:0.35924533009529114
Epoch 81,Loss:0.35854625701904297
Epoch 82,Loss:0.35781294107437134
Epoch 83,Loss:0.357073038816452
Epoch 84,Loss:0.3563689887523651
Epoch 85,Loss:0.35563886165618896
Epoch 86,Loss:0.35494092106819153
Epoch 87,Loss:0.35427770018577576
Epoch 88,Loss:0.35367846488952637
Epoch 89,Loss:0.35306182503700256
Epoch 90,Loss:0.35239094495773315
Epoch 91,Loss:0.3516080379486084
Epoch 92,Loss:0.35087117552757263
Epoch 93,Loss:0.35015198588371277
Epoch 94,Loss:0.34940671920776367
Epoch 95,Loss:0.3487066328525543
Epoch 96,Loss:0.3479807376861572
Epoch 97,Loss:0.34724101424217224
Epoch 98,Loss:0.346544474363327
Epoch 99,Loss:0.3459022045135498
Epoch 100,Loss:0.345320463180542

In [587]:
import torch
X_test = torch.tensor(X_test_scaled, dtype=torch.float32)

In [588]:
model.eval()

Sequential(
  (0): Linear(in_features=11, out_features=16, bias=True)
  (1): ReLU()
  (2): Linear(in_features=16, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=1, bias=True)
)

In [589]:
with torch.no_grad():
    outputs = model(X_test)

In [590]:
probs = torch.sigmoid(outputs)

In [591]:
preds = (probs > 0.5).float()

In [592]:
y_pred = preds.numpy()

In [593]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.86

In [594]:
print(y_train.value_counts())

Exited
0    6378
1    1622
Name: count, dtype: int64